In [1]:
import numpy as np

In [13]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr[6:9].copy()
arr_copy

array([6, 7, 8])

In [23]:
arr_copy[:]=0
arr_copy

array([0, 0, 0])

In [15]:
my2Darray = np.array(
    [
        [10,20,30,40],
        [50,60,70,80],
        [90,100,110,120]
    ]
)
print(my2Darray)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


In [21]:
print(my2Darray[0][1])
print(my2Darray[1][0])
print(my2Darray[1][1])
print(my2Darray[2][3])

20
50
60
120


In [26]:
print(my2Darray[0])
print(my2Darray[1])
print(my2Darray[2])

[10 20 30 40]
[50 60 70 80]
[ 90 100 110 120]


In [37]:
print(my2Darray[:,:]) #all 
print(my2Darray[:,0]) #first coulmn index 0
print(my2Darray[:,2]) #third coulmn index 2
print(my2Darray[:2,1:]) #
print(my2Darray[:2,1]) # #column 2 in row 1 & row 2
print(my2Darray[:2,0:1]) #column 
print(my2Darray[:3,1:])

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[10 50 90]
[ 30  70 110]
[[20 30 40]
 [60 70 80]]
[20 60]
[[10]
 [50]]
[[ 20  30  40]
 [ 60  70  80]
 [100 110 120]]


In [61]:
arr_2d = np.array(
    [
        [5, 10, 15],
        [20, 25, 30],
        [35, 40, 45]
    ]
)
print(arr_2d[0])
print(arr_2d[2])
print(arr_2d[:,0])
print(arr_2d[:,-1])

[ 5 10 15]
[35 40 45]
[ 5 20 35]
[15 30 45]


In [57]:
noRows = arr_2d.shape[0]
noColumns = arr_2d.shape[1]

In [73]:
print(arr_2d[:,noColumns-1]) #last column
arr_2d [-1] #last rows
arr_2d[noRows - 1, :] #last rows


[15 30 45]


array([35, 40, 45])

In [81]:
grid = np.arange(0,20)
print('Grid before reshape: \n',grid)
grid =grid.reshape(4,5)
print('Grid after reshape: \n',grid)
grid[:3,:2]

Grid before reshape: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Grid after reshape: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


array([[ 0,  1],
       [ 5,  6],
       [10, 11]])

In [76]:
grid = np.arange(0,16)
print('Grid before reshape: \n',grid)
grid =grid.reshape(4,4)
print('Grid after reshape: \n',grid)

Grid before reshape: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Grid after reshape: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [79]:
grid = np.arange(0,15)
print('Grid before reshape: \n',grid)
grid =grid.reshape(5,3)
print('Grid after reshape: \n',grid)

Grid before reshape: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Grid after reshape: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [85]:
print(grid[:3,:2]) #Rows from 0 to 2 , 3 not include /// Coulmn from 0 to 1, 2 not include
print(grid[3:,2:]) #Rows from 3 to last , 3 include /// Coulmn from 2 to last, 2 include
print(grid[:2,1]) #Rows from 0 to 2 , 2 not include /// Coulmn from 1
print(grid[:,-1]) #all Rows /// last Coulmn 
print(grid[::2,::2]) #skip the rows and columns one time
print(grid[::3,::3]) #skip the rows and columns two times

[[ 0  1]
 [ 5  6]
 [10 11]]
[[17 18 19]]
[1 6]
[ 4  9 14 19]
[[ 0  2  4]
 [10 12 14]]
[[ 0  3]
 [15 18]]


In [87]:
x = np.array = ([1,2,3])
y = np.array = ([3,2,1])
newarr = np.concatenate([x,y])

In [88]:
newarr

array([1, 2, 3, 3, 2, 1])

In [97]:
##concatenate
arr1 = (
    [
    [ 1, 2, 3],
    [ 4, 5, 6],
    [ 7, 8, 9],
    [10, 11, 12]
    ]
)

arr2 = (
    [
    [ 11, 12, 13],
    [ 14, 15, 16],
    [ 17, 18, 19],
    [20, 21, 22]
    ]
)
print(arr1)
print(arr2)
print(np.concatenate([arr1,arr2])) #concatenate by rows
print(np.concatenate([arr1,arr2],axis=1))#concatenate by column

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
[[11, 12, 13], [14, 15, 16], [17, 18, 19], [20, 21, 22]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [11 12 13]
 [14 15 16]
 [17 18 19]
 [20 21 22]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]
 [10 11 12 20 21 22]]


In [98]:
#split
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) #split at index 3 (from 0 to 2) &5 (from 3 to 4), the rest in the last x3
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [108]:
#Splitting 2D Array
 #Horizontal Split
grid = np.arange(16).reshape((4, 4))
print(grid)
print("\n")
upper, lower = np.vsplit(grid, [2]) #give the index rows by rows
upper, lower

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]




(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]))

In [109]:
#Splitting 2D Array
#Vertical Split
left, write = np.hsplit(grid, [1]) #give the index rows by rows
left, write

(array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]]))

In [112]:
#Taking Square Roots
arr = np.arange(11)
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [113]:
 #Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [2]:
#Random array (normal dist)
A = np.random.randn(1,100,20)
print(A)

[[[ 0.02520688 -1.60832828 -0.99730745 ...  0.67520496  1.8893565
   -0.57641805]
  [-0.74057482 -2.13499206 -0.5524465  ...  0.95537561  1.15357509
    0.63243356]
  [ 0.9735868  -0.52921578 -0.49822769 ... -1.53216869  1.46033643
   -0.78128697]
  ...
  [-0.57034603 -1.86348675 -0.77553244 ... -0.51299146 -0.19986306
   -0.14008874]
  [ 0.73621703 -0.73723567 -1.42577151 ... -1.10413711  1.51828897
   -0.54461164]
  [ 0.14165413 -1.01914394 -0.84991923 ... -0.06748523  0.88909028
   -1.41649794]]]


In [3]:
 #Create two arrays od random integer
A = np.random.randint(5,100,20) # low,high,size
B = np.random.randint(5,100,20) # low,high,size
print(A)
print(B)

[20  6 86 63 63 44 79 46 17 31 76 20 40 79 84 88 88 71 81 15]
[86 47 95 59 94 21 66 63 40 46 25  6 53 75 82 93 96  5  8 87]


In [4]:
#Addition
np.add(A,B)

array([106,  53, 181, 122, 157,  65, 145, 109,  57,  77, 101,  26,  93,
       154, 166, 181, 184,  76,  89, 102], dtype=int32)

In [5]:
#Finding max or min between two arrays
np.maximum(A,B)

array([86, 47, 95, 63, 94, 44, 79, 63, 40, 46, 76, 20, 53, 79, 84, 93, 96,
       71, 81, 87], dtype=int32)