In [6]:
import numpy as np

In [13]:
# Step 1: Create a 4x4 matrix with random numbers from 0 to 15
A = np.random.randint(0,16,(4,4))
print("Array 4x4 Matrix: \n", A)

Array 4x4 Matrix: 
 [[ 7 11  5  5]
 [15  1  4  6]
 [ 2 10 11  6]
 [ 8  5  1  8]]


In [18]:
# Step 2: Print the second column
print("Second column: \n",A[:,1])

second column: 
 [11  1 10  5]


In [20]:
# Step 3: Print the bottom two rows
print("Bottom two rows: \n",A[2:,:])

Bottom two rows: 
 [[ 2 10 11  6]
 [ 8  5  1  8]]


In [30]:
# Step 4: Extract the submatrix #like: [[6,7],[10,11]]
submatrix = A[:2, 2:4]
print("\nSubmatrix (top-right 2x2):\n", submatrix)


Submatrix (top-right 2x2):
 [[5 5]
 [4 6]]


In [25]:
# Step 5: Horizontally split the matrix into two parts (left and right)
left, right = np.vsplit(A, [2]) #give the index rows by rows
print("\nleft:\n", left)
print("\nright:\n", right)


left:
 [[ 7 11  5  5]
 [15  1  4  6]]

right:
 [[ 2 10 11  6]
 [ 8  5  1  8]]


In [26]:
# Step 6: Vertically split the matrix into two parts (upper and lower)
upper, lower = np.hsplit(A, 2) #give the index column by column
print("\nupper:\n", upper)
print("\nlower:\n", lower)


upper:
 [[ 7 11]
 [15  1]
 [ 2 10]
 [ 8  5]]

lower:
 [[ 5  5]
 [ 4  6]
 [11  6]
 [ 1  8]]


In [27]:
# Step 7: Concatenate the two right halves back together vertically
print(np.concatenate([upper,lower],axis=1))

[[ 7 11  5  5]
 [15  1  4  6]
 [ 2 10 11  6]
 [ 8  5  1  8]]
