In [1]:
import numpy as np
from numpy.random import randn

In [2]:
#Now using numpy.where
A = np.array([1,2,3,4])
B= np.array([100,200,300,400])
#Now a boolean array
condition = np.array([True,True,False,False])
answer2 = np.where(condition,A,B)
#Show
answer2

array([  1,   2, 300, 400])

In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The array is :\n",arr)
print("-----------------------------")
print("sum of all rows: ",arr.sum(0)) # sum of all rows
print("sum of all column: ",arr.sum(1)) #sum of all column

The array is :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
-----------------------------
sum of all rows:  [12 15 18]
sum of all column:  [ 6 15 24]


In [13]:
#SUM
arr.sum()

np.int64(45)

In [10]:
#Mean
arr.mean()

np.float64(5.0)

In [11]:
#Standard Deviation
arr.std()

np.float64(2.581988897471611)

In [12]:
#Variance
arr.var()

np.float64(6.666666666666667)

In [24]:
#Also any and all for processing boolean arrays
bool_arr = np.array([True,False,True])

In [28]:
#Returns True if any element in the array isTrue
bool_arr.any() #output: np.True_
#print(bool_arr.any()) #output: True

np.True_

In [26]:
#Returns True if All element in the array isTrue
bool_arr.all()

np.True_

In [31]:
#Lets learn about unique
countries = np.array(['France', 'Germany','USA','Russia','USA','Mexico','Germany'])
np.unique(countries) #عشان التكرار
#print(np.unique(countries))

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [34]:
#Test for membership
# in1d test values in one array
np.in1d(['France','USA','Sweden'],countries)

C:\Users\USER PC\AppData\Local\Temp\ipykernel_26640\3117779010.py:3: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(['France','USA','Sweden'],countries)


array([ True,  True, False])

In [35]:
np.isin(['France','USA','Sweden'],countries)

array([ True,  True, False])

The difference between np.in1d and np.isin

In [36]:
#Saving array to files
#let us see our array
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [38]:
#Lets see the original saved copy
np.load('my_array.npy')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
#Now saving and loading text files
np.savetxt('my_array_text.txt',arr,delimiter=',')

In [40]:
arr = np.loadtxt('my_array_text.txt',delimiter = ',')
arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])